version: '3'

services:
  cache:
    restart: always
    image: redis:7.0-alpine
    container_name: fdsnws-availability-cache
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
  cacher:
    build:
      context: ./
      dockerfile: Dockerfile.cacher
    container_name: fdsnws-availability-cacher
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 30s
    network_mode: "host"
    depends_on:
      - cache
    environment:
      RUNMODE: production
  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    restart: always
    container_name: fdsnws-availability-api
    network_mode: "host"
    depends_on:
      - cache
    environment:
      RUNMODE: production
