version: '3'

services:
  cache:
    restart: always
    image: redis:7.0-alpine
    container_name: fdsnws-availability-cache
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
  cacher:
    build:
      context: ./
      dockerfile: Dockerfile.cacher
    container_name: fdsnws-availability-cacher
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 30s
    ports:
      - 11211:11211
    depends_on:
      - cache
    environment:
      RUNMODE: production
      # Limit OpenBLAS threads (Fix for Cacher Crash)
      OPENBLAS_NUM_THREADS: 1
      MKL_NUM_THREADS: 1
      NUMEXPR_NUM_THREADS: 1
      OMP_NUM_THREADS: 1
    ulimits:
      nproc: 65535
    security_opt:
      - seccomp:unconfined
  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    restart: always
    container_name: fdsnws-availability-api
    ports:
      - 9001:9001
    depends_on:
      - cache
    environment:
      RUNMODE: production
      # Gateway IP (Update if needed)
      MONGODB_HOST: ${MONGODB_HOST:-172.17.0.1}
      MONGODB_PORT: ${MONGODB_PORT:-27017}
      MONGODB_USR: ${MONGODB_USR:-wfrepouser}
      MONGODB_PWD: ${MONGODB_PWD:-2023wf}
      MONGODB_NAME: ${MONGODB_NAME:-wfrepo}
      # Limit OpenBLAS threads side-effect on API
      OPENBLAS_NUM_THREADS: 1
      MKL_NUM_THREADS: 1
      NUMEXPR_NUM_THREADS: 1
      OMP_NUM_THREADS: 1
    ulimits:
      nproc: 65535
    security_opt:
      - seccomp:unconfined
